SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE lower(COLUMN_NAME) = 'html_description'
  AND TABLE_SCHEMA='YourDatabase';

ALTER DATABASE portal
    CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE portal_log
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE portal_log
    CHANGE HTML_DESCRIPTION HTML_DESCRIPTION VARCHAR(4000)
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;